apiVersion: v1
kind: ConfigMap
metadata:
  name: edc-config
data:
 
  MY_EDC_FQDN: "edc.edcaas.io"
  MY_EDC_PARTICIPANT_ID: "41:1E:30:93:58:FC:94:D0:7C:B3:4C:A4:F6:05:4A:46:CC:6E:AE:9F:keyid:41:1E:30:93:58:FC:94:D0:7C:B3:4C:A4:F6:05:4A:46:CC:6E:AE:9F"
  MY_EDC_TITLE: "EDC Connector"
  MY_EDC_DESCRIPTION: "sovity Community Edition EDC Connector"
 
  MY_EDC_CURATOR_URL: "https://example.com"
  MY_EDC_CURATOR_NAME: "Example GmbH"
 
  MY_EDC_JDBC_URL: "jdbc:postgresql://edc-db.cxk6a6weedog.eu-central-1.rds.amazonaws.com:5432/edc"
  MY_EDC_JDBC_USER: "postgres"
  MY_EDC_JDBC_PASSWORD: "gLRMDFqHJHobHxFSUpBq"
  EDC_API_AUTH_KEY: "ApiKeyDefaultValue"
  MY_EDC_MAINTAINER_URL: "https://sovity.de"
  MY_EDC_MAINTAINER_NAME: "sovity GmbH"
 
  EDC_OAUTH_TOKEN_URL: 'https://dev-daps.edcaas.io/realms/master/protocol/openid-connect/token'
  EDC_OAUTH_PROVIDER_JWKS_URL: 'https://dev-daps.edcaas.io/realms/master/protocol/openid-connect/certs'
 
  # DAPS Credentials  generate from generate_ski_aki.sh
  EDC_OAUTH_CLIENT_ID: "41:1E:30:93:58:FC:94:D0:7C:B3:4C:A4:F6:05:4A:46:CC:6E:AE:9F:keyid:41:1E:30:93:58:FC:94:D0:7C:B3:4C:A4:F6:05:4A:46:CC:6E:AE:9F"
  EDC_KEYSTORE: "/app/config/myfile.jks"
  EDC_KEYSTORE_PASSWORD: "qazxsw"
  EDC_OAUTH_CERTIFICATE_ALIAS: "myalias"
  EDC_OAUTH_PRIVATE_KEY_ALIAS: "myalias"
 
  # MY_EDC_PROTOCOL: "http://"
  # EDC_DSP_CALLBACK_ADDRESS: "http://DOMAIN/port-11003/api/dsp"
  # EDC_WEB_REST_CORS_ENABLED: "true"
  # EDC_WEB_REST_CORS_HEADERS: "origin,content-type,accept,authorization,X-Api-Key"
  # EDC_WEB_REST_CORS_ORIGINS: "*"
  # EDC_AGENT_IDENTITY_KEY: "client_id"
