name: Github actions with IAM role
on:
  push:
    branches:
      - master
  
permissions:
  contents: read 
  id-token: write

jobs:
  push_images:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone the repository
      - name: Clone repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials using IAM role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381491900147:role/EDC-ECR-PUSH-OIDC
          role-session-name: github-actions-federation
          aws-region: eu-central-1

      # Step 3: Install jq
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Step 5: Make the script executable
      - name: Set execute permission on the script
        run: chmod +x ./shell.sh

      # Step 6: Execute the shell script
      - name: Run the shell script
        run: ./shell.sh
