name: Github actions with IAM role
on: [push]

permissions:
  contents: read 
  id-token: write

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAM_ROLE }}
        role-session-name: github-actions-federation
        aws-region: ${{ secrets.REGION }}
 
    - name: List buckets
      run: aws s3 ls
